services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pk
      POSTGRES_USER: pk
      POSTGRES_PASSWORD: pktesting
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - ./pythonkr_backend:/app/pythonkr_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      POSTGRES_DB: pk
      POSTGRES_USER: pk
      POSTGRES_PASSWORD: pktesting

volumes:
  postgres_data:
