# Generated by Django 5.2.1 on 2025-06-11 12:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0006_article_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Crawling Source Name')),
                ('rss_feed_url', models.URLField(blank=True, null=True, verbose_name='RSS Feed URL')),
                ('fetch_interval', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='크롤링 주기 (시간 단위)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='RSS 피드 이름', max_length=200)),
                ('url', models.URLField(help_text='RSS 피드 URL', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('last_fetched', models.DateTimeField(blank=True, help_text='마지막 크롤링 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
            },
        ),
        migrations.CreateModel(
            name='CrawlingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Site Name')),
                ('url', models.URLField(db_index=True, help_text='사이트의 기본 URL', unique=True)),
                ('license_type', models.CharField(choices=[('MIT', 'MIT License'), ('BSD-2-Clause', 'BSD 2-Clause License'), ('Apache-2.0', 'Apache License 2.0'), ('GPL-3.0', 'GNU GPL v3'), ('LGPL-3.0', 'GNU LGPL v3'), ('MPL-2.0', 'Mozilla Public License 2.0'), ('CC0-1.0', 'CC0 1.0 Universal'), ('CC-BY-4.0', 'Creative Commons Attribution 4.0'), ('CC-BY-SA-4.0', 'Creative Commons Attribution-ShareAlike 4.0'), ('PROPRIETARY', 'Proprietary License')], default='MIT', help_text='Select the license type for the crawling source.', max_length=20)),
                ('copyright_notice_required', models.BooleanField(default=False, help_text='저작권 고지가 필요한지 여부')),
                ('copyright_link', models.URLField(blank=True, help_text='저작권 고지 링크 (필요한 경우)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(help_text='이 사이트가 속한 크롤링 소스', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='curation.crawlingsources')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Crawling Article URL')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('success', '성공'), ('failed', '실패')], default='pending', help_text='크롤링 상태', max_length=10)),
                ('crawl_creation_date', models.DateTimeField(auto_now_add=True, help_text='크롤링이 생성된 시각(자동 기록)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(help_text='이 URL이 속한 사이트', on_delete=django.db.models.deletion.CASCADE, related_name='crawl_urls', to='curation.crawlingsite')),
            ],
        ),
        migrations.CreateModel(
            name='CrawledContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='기사 제목', max_length=512)),
                ('content', models.TextField(help_text='크롤링 본문')),
                ('published_at', models.DateTimeField(blank=True, help_text='원문 게시 시각', null=True)),
                ('is_visible', models.BooleanField(default=False, help_text='라이선스/저작권 검증 결과 콘텐츠 노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crawl_url', models.ForeignKey(help_text='원본 URL 객체', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='curation.crawlurl')),
            ],
        ),
        migrations.CreateModel(
            name='RSSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=500)),
                ('link', models.URLField(help_text='아이템 URL', unique=True)),
                ('description', models.TextField(blank=True, help_text='설명')),
                ('author', models.CharField(blank=True, help_text='작성자', max_length=200)),
                ('category', models.CharField(blank=True, help_text='카테고리', max_length=200)),
                ('guid', models.CharField(blank=True, help_text='GUID', max_length=500, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, help_text='발행일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(help_text='이 아이템이 속한 RSS 피드', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curation.rssfeed')),
            ],
            options={
                'verbose_name': 'RSS Item',
                'verbose_name_plural': 'RSS Items',
                'ordering': ['-pub_date', '-created_at'],
            },
        ),
    ]
