# Generated by Django 5.2.1 on 2025-06-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0008_rssitem_crawled_content_rssitem_crawling_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='crawled_at',
            field=models.DateTimeField(blank=True, help_text='크롤링 완료 시간', null=True),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='error_message',
            field=models.TextField(blank=True, help_text='크롤링 실패 시 에러 메시지'),
        ),
    ]
