# Generated by Django 5.2.1 on 2025-06-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0009_rssitem_crawled_at_rssitem_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude'), ('gemini', 'Gemini')], help_text='LLM 서비스 제공자', max_length=20, unique=True)),
                ('priority', models.PositiveIntegerField(help_text='우선순위 (1이 가장 높음)')),
                ('is_active', models.BooleanField(default=True, help_text='서비스 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Service',
                'verbose_name_plural': 'LLM Services',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='사용 날짜')),
                ('model_name', models.CharField(help_text='사용된 모델명', max_length=100)),
                ('input_tokens', models.PositiveIntegerField(help_text='입력 토큰 수')),
                ('output_tokens', models.PositiveIntegerField(help_text='출력 토큰 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM Usage',
                'verbose_name_plural': 'LLM Usage',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
