# Generated by Django 5.2.1 on 2025-06-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0010_llmservice_llmusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmusage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='사용 날짜'),
        ),
    ]
