# Generated by Django 5.2.1 on 2025-06-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0014_rssitem_translate_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='is_newsletter',
            field=models.BooleanField(default=False, help_text='뉴스레터형 피드 여부 (개별 링크 추출이 필요한 경우)'),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='attribution_required',
            field=models.BooleanField(default=False, help_text='출처 표기 필요 여부'),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='저작권 분석 결과의 신뢰도 (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='is_translation_allowed',
            field=models.BooleanField(default=False, help_text='번역 허용 여부'),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='language',
            field=models.CharField(blank=True, help_text='감지된 콘텐츠 언어 코드 (ko, en, ja 등)', max_length=10),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='license_type',
            field=models.CharField(blank=True, help_text='분석된 라이선스 종류', max_length=50),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='reasoning',
            field=models.TextField(blank=True, help_text='AI의 저작권 분석 근거'),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='source_item',
            field=models.ForeignKey(blank=True, help_text='뉴스레터에서 추출된 경우 원본 RSSItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_items', to='curation.rssitem'),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='summary',
            field=models.TextField(blank=True, help_text='한국어 콘텐츠의 AI 생성 요약'),
        ),
    ]
