# Generated by Django 5.2.1 on 2025-10-30 02:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonkr', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PKEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_startdate', models.DateField(help_text='이벤트 시작 날짜')),
                ('event_enddate', models.DateField(blank=True, help_text='이벤트 종료 날짜 (다일 이벤트인 경우)', null=True)),
                ('time_from', models.TimeField(blank=True, help_text='시작 시간', null=True)),
                ('time_to', models.TimeField(blank=True, help_text='종료 시간', null=True)),
                ('location', models.CharField(blank=True, help_text='이벤트 장소', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='이벤트 상세 내용')),
                ('external_homepage', models.URLField(blank=True, help_text='외부 홈페이지 링크', null=True)),
                ('listed', models.BooleanField(default=False, help_text='전체 이벤트 리스트에 노출여부')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PKEvents',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='이벤트 페이지 소개 내용')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
