# Generated by Django 5.2.1 on 2025-10-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonkr', '0002_pkevent_pkevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkevent',
            name='short_description',
            field=models.CharField(blank=True, help_text='이벤트 목록에 표시될 간단한 설명', max_length=200),
        ),
    ]
