name: pk web site backend deployment

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands for update
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd python.or.kr && git pull

      - name: executing remote ssh commands for deployment
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd python.or.kr && bash deploy_prod.sh
