name: pk web site backend deployment

on:
  workflow_run:
    workflows:
      - "pk web site backend testing"
    types:
      - completed

env:
  SHA: ${{ github.sha }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands for update
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: SHA
          script: |
            cd python.or.kr && git pull

      - name: executing remote ssh commands for deployment
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: SHA
          script: |
            cd python.or.kr && bash deploy_prod.sh
