# The name of the action
name: pao web site backend testing
# When the action is triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# What to do when the action is triggered
jobs:
  testing:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
  
        - name: Install uv
          uses: astral-sh/setup-uv@v5

        - name: Install the project
          run: uv sync --all-extras --dev
  
        - name: Run tests
          run: uv run pytest 

